### ISSUE TITLE
HA onboarding fails

### ISSUE THREAD

**Issue by artmg** [tribut/homeassistant-docker-venv#1]
Hi, I tried following the instructions, using the procedures, the docker **compose** and other configs shown at https://github.com/artmg/MuGammaPi/wiki/home-assistant-docker#configuration

* compose up
    * all appears well so far
    * in under 9 seconds Home Assistant is initialized and Started
    * logs show:

```
Config directory: /config
root privileges required
Running as 1000:1000
Initializing venv in /var/tmp/venv
Starting homeassistant
[homeassistant.loader] Loaded homeassistant from homeassistant.components.homeassistant
...
[homeassistant.core] Timer:starting
```

* HA onboarding
    * enter new credentials
    * create account - 
        * dialog appears: **Ah snap, something went wrong!**
    * press OK
    * log on - it does validate credentials
	    * dialog appears: **Something went wrong loading onboarding, try refreshing**
* logs show no errors
    * onboarding appears in logs as:

```
Registered new person.person entity: person.family
Loaded toon from homeassistant.components.toon
Loaded life360 from homeassistant.components.life360
until
Loaded lifx from homeassistant.components.lifx  
```

* tried restarting server
	* no change in behaviour

Looking at the files created, they all have the correct UID:GID, so its not an obvious permissions issue.

**Comment by tribut** [comment]
Can you check the javascript console ("developer tools") of your browser for error messages when you try to go through the onboarding process?
I have a feeling your problems are unrelated to running HA as user but rather related to your nginx config. You probably have seen https://www.home-assistant.io/docs/ecosystem/nginx/ - for example you have not enabled the `proxy_set_header Host` line (needed so HA knows the correct hostname), `proxy_set_header Upgrade` (needed for websockets) and others.

**Comment by artmg** [comment]
Many thanks, @tribut you have solved my immediate issue – even if it was not actually an issue with your code :)

After the line proxy_pass line in the `nginx.conf` file I added the `proxy_set_header` directives below, and it worked like a dream - not even a peep from the browser's dev-tools java console, taking me straight into the onboarding dialog.

```
    server {
        listen 80;
        location / {
            proxy_pass http://homeassistant:8123/;
# added these directives below to resolve the 'onboarding' issue
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection “upgrade”;
        }
    }
``` 
Issue closed with gratitude
