### ISSUE TITLE
addgroup: gid '65534' in use

### ISSUE THREAD

**Issue by ptr727** [tribut/homeassistant-docker-venv#12]
Trying to run HA 0.115.0b7 in Docker on Proxmox VE (Debian) as non-root.

Using nobody / 65534 and nogroup / 65534.

Errors in log:
```
[services.d] starting services
[services.d] done.
[12:16:13] INFO: Creating user homeassistant with 65534:65534
addgroup: gid '65534' in use
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

The same nobody / nogroup works fine for other LinuxServer containers.

If I switch to nobody / users (100), I get a similar error.

Looks like addgroup failing causes the error?

**Comment by tribut** [comment]
Thanks for bringing this up. I'm currently on vacation, but I'll look into it next week.

**Comment by ozboss** [comment]
I have the same issue.
The script runs in a loop reporting:
`addgroup: gid '100' in use`

**Comment by tribut** [comment]
Sorry for taking so long. I just updated the code to work around this problem. Please let me know if everything works as expected for you.

**Comment by ptr727** [comment]
I just updated, and it is working again, thank you.
