### ISSUE TITLE
Missing s6-applyuidgid

### ISSUE THREAD

**Issue by qypea** [tribut/homeassistant-docker-venv#24]
With the update of homeassistant to 2021.7(Alpine 3.13) I ran into an error that indicated that `s6-applyuidgid` was missing on the system.
```
s6-envuidgid: fatal: unable to exec s6-applyuidgid: No such file or directory
```

I had to add `s6-ipcserver` to PACKAGES so that this program was installed and the container could start. Would it make sense to apk add this dependency as part of the `run` script or somewhere like that?

**Comment by hmoffatt** [comment]
Thanks for the workaround, that works for me too.

**Comment by ptr727** [comment]
Same problem, adding packages resolved it, where is packages documented?

**Comment by qypea** [comment]
It is described in the readme, line 12.

**Comment by maxcanna** [comment]
TY for this @qypea

**Comment by tribut** [comment]
Thank you for reporting. I've changed the script to install s6-ipcserver by default.
