### ISSUE TITLE
unable to select packages

### ISSUE THREAD

**Issue by segaura** [tribut/homeassistant-docker-venv#26]
Since a few days I am getting this error

```
hass                    | [22:22:00] INFO: Installing extra packages: iputils s6-ipcserver
hass                    | ERROR: unable to select packages:
hass                    |   iputils (no such package):
hass                    |     required by: world[iputils]
```

I am using the latest `run` file a 2021.7 HA but I am not sure the problem started with a previous HA version.

Any idea?

**Comment by maxcanna** [comment]
How did you specify the packages to be installed?
I'm using this value without any problem
```
-e "PACKAGES=iputils s6-ipcserver"
```

**Comment by segaura** [comment]
> you specify the packages to be installed?
> I'm using this value without any problem

I am using the equivalent in a `docker-compose.yml`

```
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK=007
      - PACKAGES=iputils s6-ipcserver
```

and I am getting the same error for the second package also.

My understanding is that some issue is present even without `homeassistant-docker-venv` because I am not able to start HA even without it. I am only hoping someone else is familiar with this error.

**Comment by segaura** [comment]
OK, I solved and confirm it was not a problem related to this project, I "simply" was missing the `privileged` flag that now has became more mandatory than before

```
https://github.com/home-assistant/core/issues/52647
```
