### ISSUE TITLE
s6-ipcserver requirement

### ISSUE THREAD

**Issue by devynfarr** [tribut/homeassistant-docker-venv#27]
I tried to get this running on my docker install but I kept getting the following error on docker-compose launch:

Installing package: s6-ipcserver
s6-ipcserver (missing):
ERROR: unsatisfiable constraints
    required by: world[s6-ipcserver]

I'm running Home Assistant 2021.4.2 containerized.

These are the relevant lines from from my docker-compose.yml
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant
	environment:
	  - PUID=${PUID}
	  - PGID=&{PGID}
	  - PACKAGES=iputils
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./.ssh:/ssh
	  - ./hass-config/docker/run:/etc/services.d/home-assistant/run
    restart: unless-stopped
    network_mode: host
    ports:
      - "8123:8123"
    depends_on:
      - mariadb
      - mosquitto
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00
	  
To get my install running again, I changed the following line from your run script:
REQUIRED_PACKAGES="s6-ipcserver"
to
REQUIRED_PACKAGES="iputils"

and removed iputils from my docker-compose.yml

No doubt this will have some other side effects that I'm not aware of yet.  But I wanted to pass this on in case its helpful.

**Comment by tribut** [comment]
Thanks for letting me know. Apparently my fix for #24 broke older versions of Home Assistant. I changed the logic to only install s6-ipcserver if it is required.
