### ISSUE TITLE
Consider moving VENV path under /config

### ISSUE THREAD

**Issue by dannyk81** [tribut/homeassistant-docker-venv#3]
Hey @tribut! thanks for sharing this solution, works really well!

I was wondering if it wouldn't be better to define VENV path under `/config`? 

specifically when running HASS in a container, since the default `/var/tmp/env` is not a persistent path all the packages are lost and have to be reinstalled if the container is restarted.

wdyt?

**Comment by tribut** [comment]
Hey. Thanks for the feedback!

The first iteration of this script actually had the venv under `/config`, but I decided that having an ever-growing venv (and the hassle of cleaning it up from time to time) was too much of a burden for the minimal gain of not reinstalling a few packages when HA is upgraded. Additionally, installing the packages "inside" the container most closely resembles what hass.io is doing and is therefore less likely to break.

I've added the possibility to override the location using `docker run --env VENV=/config/venv`, but I don't think that this is something we should encourage.
