### ISSUE TITLE
Fatal error when using HA 2021.9

### ISSUE THREAD

**Issue by zjean** [tribut/homeassistant-docker-venv#30]
Hi,
I just updated to the latest Home Assistant docker image, and am using the latest release of this script.
My logs now say:

```
homeassistant    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
homeassistant    | [s6-init] ensuring user provided files have correct perms...s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/home-assistant/run: Read-only file system
homeassistant    | s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/home-assistant/run: Read-only file system
```
Is that an error on my side, or something in the script?

**Comment by tribut** [comment]
Thanks for getting in touch. I am running the script without problems on 2021.9.

Sounds like you have mounted `/etc/services.d/home-assistant/run` as read-only, which causes problems?

If you need further assistance, please post the `docker-compose.yml` you are using or the full command-line of your `docker run` command.
