### ISSUE TITLE
Breaking changes in HA 0.107 / Support for s6-overlay

### ISSUE THREAD

**Issue by tribut** [tribut/homeassistant-docker-venv#5]
It appears the Home Assistant docker image will start using [s6](http://skarnet.org/software/s6/) as init system (using [s6-overlay](https://github.com/just-containers/s6-overlay)):

https://github.com/home-assistant/docker/pull/98

This means we probably have to change the mount location to the Home Assistant "service directory" and modify the scripts to use the user-switching facilities of s6.

I won't be starting to work on this until upstream has merged the change and it will probably a while before I can make the necessary change. If someone wants to start working on this, any help is appreciated.

**Comment by Chris-V** [comment]
I did not plan to look at this so early, but I was curious about how to migrate the current setup under s6-overlay. I roughly ported the current stuff and tried to go all-in with s6 structure.

You can see the result here https://github.com/Chris-V/homeassistant-docker-venv/tree/s6/s6

While the granularity is nice, mounting each file individually is not. I did that to avoid overriding potential configs from future home-assistant releases. Maybe doing the whole business logic in `/etc/services.d/home-assistant/run` would actually be easier on end-users?

Anyways, I don't think I will be able to put more time into this until next week though.

**Comment by tribut** [comment]
Thanks for looking into it. I agree that its probably less hassle for everyone if we put everything in the service directory, it's just a few lines after all.
Don't have time to test right now myself, so I'll just leave this open for now until one of us (or someone else) finds the time.

**Comment by Tuumke** [comment]
My current HA docker wont start anymore? 
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied

**Comment by tribut** [comment]
Yes, 0.107 it is currently broken. You can have a look at the files @Chris-V linked above for a quick fix, but I would recommend staying on 0.106 for the moment. It will be a few days until either of us has the time for a proper fix, it seems.

**Comment by Tuumke** [comment]
Alright, thanks. Will run on 0.106.6 then

**Comment by Tuumke** [comment]
It doesnt look like they will reopen the issues.

**Comment by Chris-V** [comment]
I have been running this in "production" for the last couple of days without issues. There is a single file that gets mounted on top of `/etc/services.d/home-assistant/run`. No entrypoint, command or "docker" user overrides required.

Obviously, booting as non-root is no longer an option because of S6.

`S6_READ_ONLY_ROOT=1` was necessary to prevent S6 from changing ownership of `setup-and-run` to root during boot. I believe this is to prevent someone breaking into the container from altering sensitive files. I will likely store mine outside of my config folder and leave it root.

https://github.com/Chris-V/homeassistant-docker-venv/commit/ca246a5b288cfcc2364f5ef1c21330b6b20d5bfd

I can open a PR later today so we can discuss about the details.

**Comment by capttrousers** [comment]
Thanks for creating this helper and for looking into the recent s6 overlay breaking change. 
In the meantime, I was able to get docker non root Home Assistant going using your venv project and sticking with 106.6 in my docker run script

```
#!/bin/bash
PATH_TO_CONFIG=<insert your config dir>
HOME_ASSISTANT_VERSION="0.106.6"
HOME_ASSISTANT_IMAGE_NAME="homeassistant/home-assistant:$HOME_ASSISTANT_VERSION"
docker run --init -d --name=home-assistant -e TZ=America/Chicago -v $PATH_TO_CONFIG:/config --net=host --user 1000:1000 $HOME_ASSISTANT_IMAGE_NAME /config/docker/run
```

**Comment by ismarslomic** [comment]
Any updates on this issue? Really waiting to be able to upgrade to latest HA version and it depends on this issue

**Comment by fanaticDavid** [comment]
I am successfully running Home Assistant 0.108.9 with the script found in PR #6

**Comment by Tuumke** [comment]
I must be doing something wrong.
Keep getting "s6-envdir: fatal: unable to envdir: No such file or directory"
Doing this on an unRaid system.

I created the docker using the template, created the folder for home-assistant, went inside and cloned the repo

````root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='home-assistant' --net='internal' --ip='172.18.0.230' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='100' -e 'PGID'='1000' -e 'PACKAGES'='iputils' -p '1823:1823/tcp' -v '/mnt/user/dockers/home-assistant':'/config':'rw' -v '/mnt/user/dockers/home-assistant/docker/run':'/etc/services.d/home-assistant/run':'rw' --dns 172.18.0.100 'homeassistant/home-assistant' /config/docker/run````

**Comment by tribut** [comment]
@Tuumke Thanks for getting in touch. Could you please [open a new issue](https://github.com/tribut/homeassistant-docker-venv/issues/new) and also include the complete docker log until you see that error so I can more easily find the cause of the problem? Thanks!

**Comment by ksurl** [comment]
does this mean we can/will soon be able to run HA as nonroot now? even if it starts the container as root, the application inside will run as designated PUID/PGID via environment variables?

**Comment by tribut** [comment]
@ksurl That is the point of this repository. Please see the [README](https://github.com/tribut/homeassistant-docker-venv#home-assistant-using-venv-in-docker) for usage information.

If you have any issues or questions, please open a new issue. Thanks!
