### ISSUE TITLE
run script not executable

### ISSUE THREAD

**Issue by hmoffatt** [tribut/homeassistant-docker-venv#9]
The run script is not marked executable in the repository. It seems to get marked as executable when I use it from Docker, so everything works, but then my git clone of this repo has unstaged changes.

**Comment by tribut** [comment]
Thanks for reminding me! I had noticed that, but somehow forget to commit a fix.

**Comment by hmoffatt** [comment]
Awesome, thanks for the quick fix and for all your work on this.

I think it's simpler to run as non-root than to depend on AppArmor as per the official HA advice. And I don't see any official way to configure AppArmor on a non-supervised "HomeAssistant Container" install anyway.
